info = audiodevinfo;
recorder = audiorecorder(44100,8,1);
F_s = 44100;
secs = 5;
recordblocking(recorder,secs);
doubleArray = getaudiodata(recorder);
audiowrite('michael.wav',doubleArray,F_s);
[y, Fs] = audioread('michael.wav');
axis = [1:F_s*secs]/F_s;
semilogy(axis, doubleArray);
xlabel('Time (s)');ylabel('Amplitude (dB)');
window = hamming(512);
N_overlap = 256;
N_fft = 1024;
[S,F,T,P] = spectrogram(y,window,N_overlap,N_fft,Fs,'yaxis');
figure;
surf(T,F,10*log10(P),'EdgeColor','none');
axis tight;
view(0,90);
colormap(jet);
set(gca,'clim',[-80,-20]);
set(gca, 'color', [0 0 0.5137]);
ylim([0 8000]);
xlabel('Time (s)');ylabel('Frequency (Hz)');
rightchannel = zeros(length(doubleArray),1);
stereo = [doubleArray, rightchannel];
audiowrite('teamG7-stereosoundfile.wav', stereo, Fs);
